[workspace]
members = [ "src/formchain_registry",
    "src/formchain_backend", "src/canister_http_router"]
resolver = "2"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.13"
hex = "0.4.3"
serde = "1"
serde_bytes = "0.11.14"
ic-ledger-types = "0.10.0"
